name: Build Rust on Nails DevContainer

on:
  push:
    branches:
    - main
    paths:
    - 'dev-env-as-code/**'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Login
        run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
      
      - name: Build Docker file
        run: |
          docker build -t purtontech/rust-on-nails-devcontainer dev-env-as-code
          docker push purtontech/rust-on-nails-devcontainer:v0.1.0