name: Spell Check

on:
  push:
    branches:
    - main
    paths:
    - 'rust-on-nails/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Spell Check
      run: docker run --rm -ti -v $HOST_PROJECT_PATH/rust-on-nails.com/content:/workdir tmaier/markdown-spellcheck:latest --report "**/*.md"
    